services:
  broker-service:
    build:
      context: ./broker-service
      dockerfile: broker-service.dockerfile
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

  task-service:
    build:
      context: ./task-service
      dockerfile: task-service.dockerfile
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "postgres://postgres:password@postgres:5432/micro_trx?sslmode=disable"

  transaction-service:
    build:
      context: ./transaction-service
      dockerfile: transaction-service.dockerfile
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "postgres://postgres:password@postgres:5432/micro_trx?sslmode=disable"

  logger-service:
    build:
      context: ./logger-service
      dockerfile: logger-service.dockerfile
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: "postgres:14.2"
    restart: always
    ports:
      - "5430:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: micro_trx
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
  mongodb:
    image: "mongo"
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INIT_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db
