version: "3"

services:
  broker-service:
    build:
      context: ./broker-service
      dockerfile: broker-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: "postgres:14.2"
    restart: always
    ports:
      - "5430:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: micro_trx
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
